[package]

# Semantic Versioning is used: https://semver.org/
version = "0.1.0"

# Description
category = "orbit"
readme  = "README.md"

# TODO: Change your package specifications
# -----------------------------------------------------------------
title = "Reward model simulations based on video language model"
author = "Levi Kennedy"
maintainer = "Levi Kennedy"
maintainer_email = "lkenned@ncsu.edu"
description="Extension for experimenting with VLM reward models"
repository = "https://github.com/levi-kennedy/orbit.vlmrew"
keywords = ["extension", "reward model", "reinforcement learning", "orbit"]
# -----------------------------------------------------------------

[dependencies]
"omni.isaac.orbit" = {}
"omni.isaac.orbit_assets" = {}
"omni.isaac.orbit_tasks" = {}
# NOTE: Add additional dependencies here

[[python.module]]
# TODO: Change your package name
# -----------------------------------------------------------------
name = "orbit.vlmrew"
# -----------------------------------------------------------------
